# Generated by Django 6.1.1 on 2026-09-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
            ],
        ),
    ]
